require './database/DatabaseInterceptor.rb'
require 'i18n'
require './lib/localization.rb'
require './lib/validation.rb'
require 'yaml'
require './console.rb'
require './lib/game.rb'
require './lib/stats.rb'
