require 'i18n'
require 'yaml'
require './lib/codebreaker/storage/storage_interceptor.rb'
require './lib/codebreaker/console.rb'
require './lib/codebreaker/localization.rb'
require './lib/codebreaker/validation.rb'
require './lib/codebreaker/statistics.rb'
require './lib/codebreaker/game.rb'
